"use strict";

const { WorkloadModuleBase } = require("@hyperledger/caliper-core");

class CreateLogWorkload extends WorkloadModuleBase {
  constructor() {
    super();
    this.logCounter = 0;
    this.documentCounter = 0;
  }

  async initializeWorkloadModule(
    workerIndex,
    totalWorkers,
    roundIndex,
    roundArguments,
    sutAdapter,
    sutContext
  ) {
    await super.initializeWorkloadModule(
      workerIndex,
      totalWorkers,
      roundIndex,
      roundArguments,
      sutAdapter,
      sutContext
    );

    this.orgName = roundArguments.orgName || "org1";
    this.collectionLog = roundArguments.collectionLog || "collectionOrg1Log";
    this.logCounter = workerIndex * 10000;
    this.documentCounter = workerIndex * 1000;

    console.log(
      `Worker ${workerIndex}: Initialized for ${this.orgName} with collection ${this.collectionLog}`
    );
  }

  async submitTransaction() {
    this.logCounter++;
    this.documentCounter = Math.floor(this.logCounter / 10);

    const documentID = `DOC-${this.documentCounter}`;
    const actorID = `ACTOR-${Math.floor(Math.random() * 100)}`;
    const actorName = `User ${Math.floor(Math.random() * 50)}`;
    const actions = [
      "CREATE",
      "VIEW",
      "SIGN",
      "UPDATE",
      "DELETE",
      "APPROVE",
      "REJECT",
    ];
    const action = actions[Math.floor(Math.random() * actions.length)];

    // IMPORTANT: Match the structure your chaincode expects
    const transientMap = {
      log: Buffer.from(
        // CHANGED from log_data to log
        JSON.stringify({
          collectionLog: this.collectionLog, // Added - chaincode needs this
          documentID: documentID,
          actorID: actorID,
          actorName: actorName,
          action: action,
          // Note: ID and timestamp are auto-generated by chaincode
        })
      ),
    };

    const request = {
      contractId: "basic",
      contractFunction: "CreatePrivateLogDocument",
      contractArguments: [], // Your chaincode doesn't use args, only transient data
      transientMap: transientMap,
      readOnly: false,
    };

    try {
      await this.sutAdapter.sendRequests(request);
    } catch (error) {
      console.error(`Error creating log: ${error.message}`);
      throw error;
    }
  }

  async cleanupWorkloadModule() {
    console.log(`Worker completed: Created ${this.logCounter} logs`);
  }
}

function createWorkloadModule() {
  return new CreateLogWorkload();
}

module.exports.createWorkloadModule = createWorkloadModule;
