networks:
  fabric_esign:
    external: true

services:
  ca_orderer:
    image: hyperledger/fabric-ca:1.5
    container_name: ca_orderer
    ports:
      - "9054:9054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
      - FABRIC_CA_SERVER_CSR_CN=ca_orderer
      - FABRIC_CA_SERVER_CSR_HOSTS=ca_orderer,localhost
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca-server-config:/etc/hyperledger/fabric-ca-server
    networks:
      - fabric_esign
